### PR TITLE
Ft approve cart details

### PR DESCRIPTION
**Pull request by tolls-3**
## Description
Seller can approve buyers cart.
## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/Rr5FG4s0/127-seller-approves-or-disapproves-a-cart-detail

### CODE REVIEW

**Comment by tolls-3** [comment]
[Seller approves or disapproves a cart detail](https://trello.com/c/Rr5FG4s0/127-seller-approves-or-disapproves-a-cart-detail)

**Review by DimejiAre — APPROVED** [review]
@tolls-3 Remove console.logs

**Review by aapetsi — APPROVED** [review]
Looks good

**Comment by kip-guile** [comment]
Looks good

**Pull request merged**
